image:
  pullPolicy: Always

service:
  targetPort: 4000

secretEnv:
  WEATHER_API_KEY:
    secretName: vuego-demoapp
    secretKey: weatherKey
  IPSTACK_API_KEY:
    secretName: vuego-demoapp
    secretKey: ipStackKey

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  host: ${{ env.host }}
  tls: 
    enabled: true
    secretName: kube-benco-io-cert